version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "6432:5432"

  web:
    build: .
    container_name: web
    restart: always
    command: gunicorn weatherreminder.wsgi:application --bind 0.0.0.0:80
    volumes:
      - .:/usr/src/app
    ports:
      - "80:80"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    env_file:
      - ./.env
    depends_on:
      - pgdb
      - redis

  celery-worker:
    build: .
    command: celery -A weatherreminder worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  celery-beat:
    build: .
    command: celery -A weatherreminder beat -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - web
      - redis

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  flower:
    image: mher/flower:2.0.0
    command: celery flower
    volumes:
      - .:/usr/src/app
    ports:
      - "5557:5555"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - celery-worker
      - redis

volumes:
  postgres_data: