FROM python:3.10.3-alpine

ENV PYTHONDONTWRITEBITECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

RUN apk update && apk add build-base postgresql-dev gcc jpeg-dev zlib-dev freetype-dev gettext

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

COPY . /usr/src/app

ENTRYPOINT ["sh", "entrypoint.sh"]
# ENTRYPOINT ["/usr/src/app/entrypoint.sh"]